apiVersion: v1
kind: Service
metadata:
  name: automatizator-service
spec:
  selector:
    app: automatizator 
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer
apiVersion: apps/v1
kind: Deployment
metadata:
  name: automatizator
spec:
  selector:
    matchLabels:
      app: automatizator 
  replicas: 4
  template:
    metadata:
      labels:
        app: automatizator 
    spec:
      containers:
      - name: automatizator
        image: automatizator 
    :latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000